### ISSUE TITLE
Leaning left of the heading text in preview mode

### ISSUE THREAD

**Issue by subi54** [RuslanGagushin/Tokyo-Night-Obsidian-Theme#1]
Hey,

First off, love the theme.

~~Second off, as you can see in the attached gif, the preview mode heading kinda leans towards the left which mars the switching experience between the edit and preview modes. Is there a way to get it aligned with the edit mode?~~ I think it's more like the padding of the ol misaligns with the heading that gave me that illusion. I tried with non li notes and they look good. I have added `ol { padding-left: 0px;}` but it hides the first number from 3 digit lists. So, if there any solution, that'd be nice.

The highlight color is not very visible.

![IHt6tVFjfk](https://user-images.githubusercontent.com/8841727/126272824-9266b919-ecae-4542-9323-8240699c2750.gif)

**Comment by RuslanGagushin** [comment]
Hey!
Can you send the example of highlight text?
I will think about list items

**Comment by RuslanGagushin** [comment]
![image](https://user-images.githubusercontent.com/15202306/126294845-6db5849d-fe76-448a-a08e-f6754d8b1eb1.png)
li elements done
